import java.util.Scanner;

public class Discoteca {
    public static void main(String[] args) {
        Scanner lector = new Scanner(System.in);

        Cancion[] canciones = {
                new Cancion("Shape of You", "Ed Sheeran", "Pop", 234, "Divide", 2017),
                new Cancion("Blinding Lights", "The Weeknd", "Synthpop", 200, "After Hours", 2019),
                new Cancion("Bohemian Rhapsody", "Queen", "Rock", 355, "A Night at the Opera", 1975),
                new Cancion("Billie Jean", "Michael Jackson", "Pop", 294, "Thriller", 1982),
                new Cancion("Smells Like Teen Spirit", "Nirvana", "Grunge", 301, "Nevermind", 1991),
                new Cancion("Uptown Funk", "Mark Ronson ft. Bruno Mars", "Funk Pop", 270, "Uptown Special", 2014),
                new Cancion("Rolling in the Deep", "Adele", "Soul/Pop", 228, "21", 2010),
                new Cancion("Hotel California", "Eagles", "Rock", 391, "Hotel California", 1976),
                new Cancion("Highway to Hell", "AC/DC", "Hard Rock", 208, "Highway to Hell", 1979),
                new Cancion("Despacito", "Luis Fonsi & Daddy Yankee", "Reggaeton", 228, "Vida", 2017),
                new Cancion("Seven Nation Army", "The White Stripes", "Alternative Rock", 231, "Elephant", 2003),
                new Cancion("Hey Jude", "The Beatles", "Rock", 431, "Hey Jude", 1968),
                new Cancion("Poker Face", "Lady Gaga", "Electropop", 238, "The Fame", 2008),
                new Cancion("Someone Like You", "Adele", "Soul", 285, "21", 2011),
                new Cancion("Wonderwall", "Oasis", "Britpop", 258, "(What's the Story) Morning Glory?", 1995),
                new Cancion("Thunderstruck", "AC/DC", "Rock", 292, "The Razors Edge", 1990),
                new Cancion("Beat It", "Michael Jackson", "Rock/Pop", 258, "Thriller", 1982),
                new Cancion("Hips Don't Lie", "Shakira ft. Wyclef Jean", "Latin Pop", 218, "Oral Fixation vol. 2", 2006),
                new Cancion("Viva la Vida", "Coldplay", "Alternative", 242, "Viva la Vida", 2008),
                new Cancion("Take On Me", "a-ha", "Pop", 225, "Hunting High and Low", 1985),
                new Cancion("Bad Guy", "Billie Eilish", "Electropop", 194, "When We All Fall Asleep, Where Do We Go?", 2019),
                new Cancion("Shallow", "Lady Gaga & Bradley Cooper", "Pop", 216, "A Star Is Born", 2018),
                new Cancion("Lose Yourself", "Eminem", "Rap", 326, "8 Mile", 2002),
                new Cancion("Numb", "Linkin Park", "Nu Metal", 185, "Meteora", 2003),
                new Cancion("Halo", "Beyoncé", "Pop", 261, "I Am... Sasha Fierce", 2008),
                new Cancion("Can't Stop", "Red Hot Chili Peppers", "Funk Rock", 271, "By the Way", 2002),
                new Cancion("Africa", "Toto", "Rock/Pop", 295, "Toto IV", 1982),
                new Cancion("Radioactive", "Imagine Dragons", "Alternative", 186, "Night Visions", 2012),
                new Cancion("Beat It", "Michael Jackson", "Pop/Rock", 258, "Thriller", 1982),
                new Cancion("Every Breath You Take", "The Police", "Rock", 258, "Synchronicity", 1983),
                new Cancion("Sweet Child O' Mine", "Guns N' Roses", "Hard Rock", 356, "Appetite for Destruction", 1987),
                new Cancion("Closer", "The Chainsmokers ft. Halsey", "EDM", 244, "Collage", 2016),
                new Cancion("Livin' on a Prayer", "Bon Jovi", "Rock", 249, "Slippery When Wet", 1986),
                new Cancion("Senorita", "Shawn Mendes & Camila Cabello", "Pop", 191, "Romance", 2019),
                new Cancion("Old Town Road", "Lil Nas X", "Country Rap", 157, "7", 2019),
                new Cancion("Like a Rolling Stone", "Bob Dylan", "Folk Rock", 369, "Highway 61 Revisited", 1965),
                new Cancion("Believer", "Imagine Dragons", "Alternative", 204, "Evolve", 2017),
                new Cancion("Titanium", "David Guetta ft. Sia", "EDM", 245, "Nothing but the Beat", 2011),
                new Cancion("Thinking Out Loud", "Ed Sheeran", "Pop", 281, "x", 2014),
                new Cancion("Don't Stop Me Now", "Queen", "Rock", 210, "Jazz", 1978),
                new Cancion("Enter Sandman", "Metallica", "Metal", 331, "Metallica", 1991),
                new Cancion("Chandelier", "Sia", "Pop", 216, "1000 Forms of Fear", 2014),
                new Cancion("Happy", "Pharrell Williams", "Pop", 233, "Girl", 2013),
                new Cancion("Billie Jean", "Michael Jackson", "Pop", 294, "Thriller", 1982),
                new Cancion("I Gotta Feeling", "Black Eyed Peas", "Dance-Pop", 288, "The E.N.D.", 2009),
                new Cancion("Bad Romance", "Lady Gaga", "Pop", 295, "The Fame Monster", 2009),
                new Cancion("Grenade", "Bruno Mars", "Pop", 223, "Doo-Wops & Hooligans", 2010),
                new Cancion("Born to Run", "Bruce Springsteen", "Rock", 279, "Born to Run", 1975),
                new Cancion("Paint It Black", "The Rolling Stones", "Rock", 200, "Aftermath", 1966),
                new Cancion("Firework", "Katy Perry", "Pop", 228, "Teenage Dream", 2010),
                new Cancion("Yesterday", "The Beatles", "Rock/Pop", 125, "Help!", 1965),
                new Cancion("Thriller", "Michael Jackson", "Pop", 357, "Thriller", 1982),
                new Cancion("Dance Monkey", "Tones and I", "Pop", 209, "The Kids Are Coming", 2019),
                new Cancion("My Heart Will Go On", "Celine Dion", "Pop", 280, "Let's Talk About Love", 1997),
                new Cancion("Rockstar", "Post Malone ft. 21 Savage", "Trap", 218, "Beerbongs & Bentleys", 2017),
                new Cancion("Stronger", "Kanye West", "Rap", 311, "Graduation", 2007),
                new Cancion("Tusa", "Karol G & Nicki Minaj", "Reggaeton", 200, "KG0516", 2019),
                new Cancion("Take Me to Church", "Hozier", "Indie Rock", 241, "Hozier", 2013),
                new Cancion("Blowin' in the Wind", "Bob Dylan", "Folk", 167, "The Freewheelin’ Bob Dylan", 1963),
                new Cancion("Sultans of Swing", "Dire Straits", "Rock", 346, "Dire Straits", 1978),
                new Cancion("Bad Habits", "Ed Sheeran", "Pop", 231, "=", 2021),
                new Cancion("Call Me Maybe", "Carly Rae Jepsen", "Pop", 193, "Kiss", 2012),
                new Cancion("Lose Control", "Teddy Swims", "Soul/Pop", 201, "I've Tried Everything...", 2023),
                new Cancion("Zombie", "The Cranberries", "Alternative Rock", 307, "No Need to Argue", 1994),
                new Cancion("Without Me", "Eminem", "Rap", 290, "The Eminem Show", 2002),
                new Cancion("Sugar", "Maroon 5", "Pop", 235, "V", 2015),
                new Cancion("Riptide", "Vance Joy", "Indie Folk", 203, "Dream Your Life Away", 2013),
                new Cancion("Dream On", "Aerosmith", "Rock", 273, "Aerosmith", 1973),
                new Cancion("Counting Stars", "OneRepublic", "Pop", 257, "Native", 2013),
                new Cancion("Thunder", "Imagine Dragons", "Alternative", 187, "Evolve", 2017),
                new Cancion("The Scientist", "Coldplay", "Alternative", 311, "A Rush of Blood to the Head", 2002),
                new Cancion("Misery Business", "Paramore", "Pop Punk", 212, "Riot!", 2007),
                new Cancion("Levitating", "Dua Lipa", "Pop", 203, "Future Nostalgia", 2020),
                new Cancion("Stayin' Alive", "Bee Gees", "Disco", 284, "Saturday Night Fever", 1977),
                new Cancion("Toxic", "Britney Spears", "Pop", 199, "In the Zone", 2003),
                new Cancion("Eye of the Tiger", "Survivor", "Rock", 245, "Eye of the Tiger", 1982),
                new Cancion("Wrecking Ball", "Miley Cyrus", "Pop", 221, "Bangerz", 2013),
                new Cancion("Wake Me Up", "Avicii", "EDM", 247, "True", 2013),
                new Cancion("Californication", "Red Hot Chili Peppers", "Rock", 322, "Californication", 1999),
                new Cancion("All of Me", "John Legend", "R&B", 269, "Love in the Future", 2013),
                new Cancion("Mr. Brightside", "The Killers", "Rock", 222, "Hot Fuss", 2003),
                new Cancion("New Rules", "Dua Lipa", "Pop", 209, "Dua Lipa", 2017),
                new Cancion("La Bamba", "Los Lobos", "Rock Latino", 165, "La Bamba", 1987),
                new Cancion("Sicko Mode", "Travis Scott", "Trap", 312, "Astroworld", 2018),
                new Cancion("Your Song", "Elton John", "Soft Rock", 242, "Elton John", 1970),
                new Cancion("I Want to Hold Your Hand", "The Beatles", "Rock", 145, "Meet the Beatles!", 1963),
                new Cancion("Gangnam Style", "PSY", "K-Pop", 219, "Psy 6", 2012),
                new Cancion("Smooth", "Santana ft. Rob Thomas", "Latin Rock", 298, "Supernatural", 1999),
                new Cancion("Dynamite", "BTS", "K-Pop", 199, "BE", 2020),
                new Cancion("Boulevard of Broken Dreams", "Green Day", "Rock", 260, "American Idiot", 2004),
                new Cancion("I Will Always Love You", "Whitney Houston", "Pop", 273, "The Bodyguard", 1992),
                new Cancion("Single Ladies", "Beyoncé", "R&B", 194, "I Am... Sasha Fierce", 2008),
                new Cancion("Clocks", "Coldplay", "Alternative", 307, "A Rush of Blood to the Head", 2002),
                new Cancion("Radio Ga Ga", "Queen", "Pop Rock", 354, "The Works", 1984),
                new Cancion("Sweet Dreams", "Eurythmics", "Synthpop", 215, "Sweet Dreams", 1983),
                new Cancion("Forget You", "CeeLo Green", "Soul Pop", 219, "The Lady Killer", 2010),
                new Cancion("Happy Together", "The Turtles", "Pop Rock", 161, "Happy Together", 1967),
                new Cancion("Shape of My Heart", "Sting", "Soft Rock", 270, "Ten Summoner's Tales", 1993),
                new Cancion("My Universe", "Coldplay & BTS", "Pop", 229, "Music of the Spheres", 2021),
                new Cancion("Break My Heart", "Dua Lipa", "Pop", 223, "Future Nostalgia", 2020),
                new Cancion("All Star", "Smash Mouth", "Alt Rock", 201, "Astro Lounge", 1999),
                new Cancion("I Kissed a Girl", "Katy Perry", "Pop", 179, "One of the Boys", 2008),
                new Cancion("Closer to Fine", "Indigo Girls", "Folk Rock", 271, "Indigo Girls", 1989),
                new Cancion("Zombie Nation", "Kernkraft 400", "Techno", 320, "Leichenschmaus", 1999),
                new Cancion("Summer of '69", "Bryan Adams", "Rock", 215, "Reckless", 1984),
                new Cancion("Royals", "Lorde", "Electropop", 211, "Pure Heroine", 2013),
                new Cancion("Rather Be", "Clean Bandit ft. Jess Glynne", "EDM", 247, "New Eyes", 2014),
                new Cancion("Say You Won't Let Go", "James Arthur", "Pop", 211, "Back from the Edge", 2016),
                new Cancion("Faded", "Alan Walker", "EDM", 212, "Different World", 2015),
                new Cancion("Runaway", "AURORA", "Pop", 233, "All My Demons...", 2015),
                new Cancion("Heat Waves", "Glass Animals", "Indie Pop", 238, "Dreamland", 2020),
                new Cancion("Whatever It Takes", "Imagine Dragons", "Alternative", 201, "Evolve", 2017),
                new Cancion("All the Stars", "Kendrick Lamar & SZA", "Hip-Hop", 232, "Black Panther", 2018),
                new Cancion("Lucid Dreams", "Juice WRLD", "Rap", 239, "Goodbye & Good Riddance", 2018),
                new Cancion("Bad", "Michael Jackson", "Pop", 247, "Bad", 1987),
                new Cancion("Heat Above", "Greta Van Fleet", "Rock", 328, "The Battle at Garden’s Gate", 2021),
                new Cancion("Creep", "Radiohead", "Alternative Rock", 238, "Pablo Honey", 1993),
                new Cancion("Domino", "Jessie J", "Pop", 230, "Who You Are", 2011),
                new Cancion("Good 4 U", "Olivia Rodrigo", "Pop Punk", 178, "SOUR", 2021),
                new Cancion("Dance the Night", "Dua Lipa", "Pop", 177, "Barbie", 2023),
                new Cancion("Your Love", "The Outfield", "Rock", 203, "Play Deep", 1985),
                new Cancion("Part of Me", "Katy Perry", "Pop", 227, "Teenage Dream", 2010),
                new Cancion("Iris", "Goo Goo Dolls", "Rock", 266, "Dizzy Up the Girl", 1998),
                new Cancion("Shake It Off", "Taylor Swift", "Pop", 242, "1989", 2014),
                new Cancion("Message in a Bottle", "The Police", "Rock", 300, "Reggatta de Blanc", 1979),
                new Cancion("Let It Be", "The Beatles", "Rock", 243, "Let It Be", 1970),
                new Cancion("Can't Feel My Face", "The Weeknd", "Pop", 214, "Beauty Behind the Madness", 2015),
                new Cancion("Sugar, We're Goin Down", "Fall Out Boy", "Pop Punk", 228, "From Under the Cork Tree", 2005),
                new Cancion("The Middle", "Zedd, Maren Morris, Grey", "EDM", 184, "Single", 2018),
                new Cancion("The Nights", "Avicii", "EDM", 176, "The Days/Nights", 2014),
                new Cancion("Born This Way", "Lady Gaga", "Pop", 260, "Born This Way", 2011),
                new Cancion("Stressed Out", "Twenty One Pilots", "Alt/Pop", 202, "Blurryface", 2015),
                new Cancion("Take It Easy", "Eagles", "Rock", 193, "Eagles", 1972),
                new Cancion("Roxanne", "The Police", "Rock", 191, "Outlandos d'Amour", 1978),
                new Cancion("Flowers", "Miley Cyrus", "Pop", 200, "Endless Summer Vacation", 2023),
                new Cancion("As It Was", "Harry Styles", "Pop", 167, "Harry's House", 2022),
                new Cancion("Anti-Hero", "Taylor Swift", "Pop", 200, "Midnights", 2022),
                new Cancion("Don't Speak", "No Doubt", "Rock", 253, "Tragic Kingdom", 1995),
                new Cancion("Starboy", "The Weeknd", "R&B", 230, "Starboy", 2016),
                new Cancion("Radioactive", "Imagine Dragons", "Alt Rock", 186, "Night Visions", 2012),
                new Cancion("Blow", "Ed Sheeran, Bruno Mars, Chris Stapleton", "Rock", 223, "No.6 Collaborations", 2019),
                new Cancion("Strangers", "Kenya Grace", "Electronic", 174, "Single", 2023),
                new Cancion("Wonder", "Shawn Mendes", "Pop", 174, "Wonder", 2020),
                new Cancion("Smooth Criminal", "Michael Jackson", "Pop", 257, "Bad", 1987),
                new Cancion("Tequila", "The Champs", "Surf Rock", 153, "Single", 1958),
                new Cancion("I Just Called to Say I Love You", "Stevie Wonder", "Soul", 278, "The Woman in Red", 1984),
                new Cancion("Flashdance... What a Feeling", "Irene Cara", "Pop", 243, "Flashdance", 1983),
                new Cancion("Havana", "Camila Cabello", "Latin Pop", 217, "Camila", 2017),
                new Cancion("Bad Blood", "Taylor Swift", "Pop", 211, "1989", 2015),
                new Cancion("Happy Now", "Zedd & Elley Duhé", "EDM", 210, "Single", 2018),
                new Cancion("I Wanna Dance with Somebody", "Whitney Houston", "Pop", 293, "Whitney", 1987),
                new Cancion("Smack That", "Akon ft. Eminem", "Hip-Hop", 236, "Konvicted", 2006),
                new Cancion("Moves Like Jagger", "Maroon 5 & Christina Aguilera", "Pop", 201, "Hands All Over", 2011),
                new Cancion("In The End", "Linkin Park", "Nu Metal", 217, "Hybrid Theory", 2000),
                new Cancion("Happier", "Marshmello ft. Bastille", "EDM", 214, "Joytime II", 2018),
                new Cancion("Le Freak", "Chic", "Disco", 328, "Risqué", 1978),
                new Cancion("Thunder", "AC/DC", "Rock", 273, "The Razors Edge", 1990),
                new Cancion("Pompeii", "Bastille", "Indie Pop", 217, "Bad Blood", 2013),
                new Cancion("Dance with Me", "Orleans", "Soft Rock", 215, "Let There Be Music", 1975),
                new Cancion("On Top of the World", "Imagine Dragons", "Indie Pop", 216, "Night Visions", 2012),
                new Cancion("3 Nights", "Dominic Fike", "Indie Pop", 178, "Don't Forget About Me", 2018),
                new Cancion("Physical", "Dua Lipa", "Pop", 194, "Future Nostalgia", 2020),
                new Cancion("Treasure", "Bruno Mars", "Funk/Pop", 178, "Unorthodox Jukebox", 2012),
                new Cancion("Rude", "MAGIC!", "Reggae Fusion", 224, "Don't Kill the Magic", 2013),
                new Cancion("Waiting on the World to Change", "John Mayer", "Pop Rock", 208, "Continuum", 2006),
                new Cancion("Counting Blue Cars", "Dishwalla", "Alt Rock", 283, "Pet Your Friends", 1995),
                new Cancion("Get Lucky", "Daft Punk ft. Pharrell", "Funk/Disco", 248, "Random Access Memories", 2013),
                new Cancion("Thunderclouds", "LSD", "Pop", 217, "LSD", 2018),
                new Cancion("Something Just Like This", "The Chainsmokers & Coldplay", "EDM", 248, "Memories...Do Not Open", 2017),
                new Cancion("What Is Love", "Haddaway", "Eurodance", 282, "The Album", 1993),
                new Cancion("The Final Countdown", "Europe", "Rock", 301, "The Final Countdown", 1986),
                new Cancion("Paradise", "Coldplay", "Alternative", 278, "Mylo Xyloto", 2011),
                new Cancion("Take My Breath", "The Weeknd", "Synthpop", 220, "Dawn FM", 2022),
                new Cancion("My Songs Know...", "Fall Out Boy", "Alt Rock", 207, "Save Rock and Roll", 2013),
                new Cancion("Shotgun", "George Ezra", "Pop", 219, "Staying at Tamara's", 2018),
                new Cancion("Belong", "Cash Cash & Dashboard Confessional", "EDM", 180, "Single", 2016),
                new Cancion("We Are Young", "fun. ft. Janelle Monáe", "Indie", 255, "Some Nights", 2012),
                new Cancion("Sunroof", "Nicky Youre & Dazy", "Pop", 137, "Single", 2022),
                new Cancion("A Sky Full of Stars", "Coldplay", "EDM", 266, "Ghost Stories", 2014),
                new Cancion("Good Life", "OneRepublic", "Pop", 261, "Waking Up", 2009),
                new Cancion("Duele el Corazón", "Enrique Iglesias", "Latin Pop", 209, "Single", 2016),
                new Cancion("Thunder in Your Heart", "John Farnham", "Rock", 239, "Rad", 1986),
                new Cancion("Pepas", "Farruko", "Reggaeton", 256, "La 167", 2021),
                new Cancion("La Camisa Negra", "Juanes", "Latin Rock", 216, "Mi Sangre", 2004),
                new Cancion("Vivir Mi Vida", "Marc Anthony", "Salsa", 256, "Marc Anthony", 2013),
                new Cancion("La Bicicleta", "Shakira & Carlos Vives", "Latin Pop", 223, "Vives", 2016),
                new Cancion("Beso", "Rosalía & Rauw Alejandro", "Pop", 189, "RR", 2023),
                new Cancion("Tacones Rojos", "Sebastián Yatra", "Latin Pop", 179, "Dharma", 2021),
                new Cancion("Provenza", "Karol G", "Latin Pop", 197, "Mañana Será Bonito", 2022),
                new Cancion("Felices los 4", "Maluma", "Reggaeton", 234, "F.A.M.E.", 2017),
                new Cancion("Tu Sonrisa", "Elvis Crespo", "Merengue", 213, "Suavemente", 1998),
                new Cancion("Dákiti", "Bad Bunny & Jhay Cortez", "Reggaeton", 208, "El Último Tour del Mundo", 2020),
                new Cancion("Me Rehúso", "Danny Ocean", "Reggaeton", 199, "54+1", 2016),
                new Cancion("Bailando", "Enrique Iglesias", "Latin Pop", 250, "Sex and Love", 2014),
                new Cancion("Torero", "Chayanne", "Pop Latino", 214, "Grandes Éxitos", 2002),
                new Cancion("Rayando el Sol", "Maná", "Rock Latino", 251, "Falta Amor", 1990),
                new Cancion("Sí", "Julieta Venegas", "Pop Latino", 209, "Sí", 2003),
                new Cancion("Labios Compartidos", "Maná", "Rock Latino", 289, "Amar es Combatir", 2006),
                new Cancion("Llorar", "Jesse & Joy", "Pop Latino", 247, "¿Con Quién Se Queda el Perro?", 2011),
                new Cancion("Corazón Espinado", "Santana & Maná", "Latin Rock", 256, "Supernatural", 1999) };

            lector.close();
    }       // Cierro el main
}